services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Shopsys\ProductFeed\PersooBundle\:
        resource: '../../*'

    Shopsys\ProductFeed\PersooBundle\PersooFeed:
        tags:
            - { name: shopsys.feed, hours: '*', minutes: '15' }
